# Generated by Django 5.2.7 on 2025-10-28 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('item_seq', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=500, verbose_name='약 이름')),
                ('item_name_eng', models.CharField(blank=True, max_length=500, null=True, verbose_name='영문명')),
                ('entp_name', models.CharField(max_length=300, verbose_name='제조회사')),
                ('effect', models.TextField(blank=True, null=True, verbose_name='효능/효과')),
                ('usage', models.TextField(blank=True, null=True, verbose_name='사용법')),
                ('warning_critical', models.TextField(blank=True, null=True, verbose_name='중요 경고')),
                ('warning_general', models.TextField(blank=True, null=True, verbose_name='일반 경고')),
                ('interaction', models.TextField(blank=True, null=True, verbose_name='상호작용')),
                ('side_effect', models.TextField(blank=True, null=True, verbose_name='부작용')),
                ('storage', models.TextField(blank=True, null=True, verbose_name='보관법')),
                ('main_ingredient', models.TextField(blank=True, null=True, verbose_name='주성분')),
                ('ingredient_count', models.IntegerField(blank=True, null=True, verbose_name='성분 개수')),
                ('class_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='분류')),
                ('product_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='제품 타입')),
                ('edi_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='EDI 코드')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '약물 정보',
                'verbose_name_plural': '약물 정보',
                'db_table': 'medicines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OCRImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100, verbose_name='이미지')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ocr_result', models.TextField(blank=True, null=True, verbose_name='OCR 결과')),
                ('extracted_medicine_names', models.TextField(blank=True, null=True, verbose_name='추출된 약 이름')),
            ],
            options={
                'verbose_name': 'OCR 이미지',
                'verbose_name_plural': 'OCR 이미지',
                'db_table': 'ocr_ocrimage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, max_length=100, null=True, verbose_name='복용량')),
                ('frequency', models.CharField(blank=True, max_length=100, null=True, verbose_name='복용 횟수')),
                ('days', models.CharField(blank=True, max_length=50, null=True, verbose_name='복용 일수')),
                ('prescription_date', models.DateField(blank=True, null=True, verbose_name='처방일')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('pharmacy_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='약국명')),
                ('hospital_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='병원명')),
                ('is_completed', models.BooleanField(default=False, verbose_name='복용 완료')),
            ],
            options={
                'verbose_name': '사용자 복용 약',
                'verbose_name_plural': '사용자 복용 약',
                'db_table': 'user_medications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccessibilityInfo',
            fields=[
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='carepill.medicine')),
                ('video_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='영상 URL')),
                ('has_audio', models.BooleanField(default=False, verbose_name='음성 지원')),
                ('has_sign_language', models.BooleanField(default=False, verbose_name='수어 지원')),
                ('effect_tts', models.TextField(blank=True, null=True, verbose_name='효능 TTS')),
                ('usage_tts', models.TextField(blank=True, null=True, verbose_name='사용법 TTS')),
                ('warning_tts', models.TextField(blank=True, null=True, verbose_name='경고 TTS')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='바코드')),
                ('std_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='표준 코드')),
            ],
            options={
                'verbose_name': '접근성 정보',
                'verbose_name_plural': '접근성 정보',
                'db_table': 'accessibility_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PillIdentification',
            fields=[
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='carepill.medicine')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='이미지 URL')),
                ('shape', models.CharField(blank=True, max_length=100, null=True, verbose_name='모양')),
                ('color_front', models.CharField(blank=True, max_length=100, null=True, verbose_name='앞면 색상')),
                ('color_back', models.CharField(blank=True, max_length=100, null=True, verbose_name='뒷면 색상')),
                ('print_front', models.CharField(blank=True, max_length=200, null=True, verbose_name='앞면 각인')),
                ('print_back', models.CharField(blank=True, max_length=200, null=True, verbose_name='뒷면 각인')),
                ('length_long', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='장축 길이')),
                ('length_short', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='단축 길이')),
                ('thickness', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='두께')),
                ('line_front', models.CharField(blank=True, max_length=100, null=True, verbose_name='앞면 분할선')),
                ('line_back', models.CharField(blank=True, max_length=100, null=True, verbose_name='뒷면 분할선')),
                ('shape_code', models.IntegerField(blank=True, null=True, verbose_name='모양 코드')),
            ],
            options={
                'verbose_name': '알약 식별 정보',
                'verbose_name_plural': '알약 식별 정보',
                'db_table': 'pill_identification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VoiceUserVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_file', models.CharField(max_length=100, verbose_name='음성 파일')),
                ('voice_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ElevenLabs Voice ID')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='재생 시간')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 음성',
                'verbose_name_plural': '사용자 음성',
                'db_table': 'voice_user_voice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VoiceTTSCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='텍스트')),
                ('text_hash', models.CharField(max_length=64, verbose_name='텍스트 해시')),
                ('audio_file', models.CharField(max_length=100, verbose_name='오디오 파일')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='재생 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_at', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0, verbose_name='접근 횟수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'TTS 캐시',
                'verbose_name_plural': 'TTS 캐시',
                'db_table': 'voice_tts_cache',
                'managed': True,
                'unique_together': {('user', 'text_hash')},
            },
        ),
    ]
