# Generated by Django 5.2.7 on 2025-10-10 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_file', models.FileField(help_text='5-10초 음성 샘플 (WAV 권장)', upload_to='user_voices/')),
                ('duration_seconds', models.FloatField(blank=True, help_text='음성 샘플 길이(초)', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='활성 상태')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sample', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 음성',
                'verbose_name_plural': '사용자 음성 샘플',
                'db_table': 'voice_user_voice',
            },
        ),
        migrations.CreateModel(
            name='TTSCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='TTS 텍스트')),
                ('text_hash', models.CharField(db_index=True, help_text='텍스트 MD5 해시', max_length=64)),
                ('audio_file', models.FileField(help_text='생성된 음성 파일', upload_to='tts_cache/')),
                ('duration_seconds', models.FloatField(blank=True, help_text='음성 길이(초)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_at', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0, help_text='접근 횟수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_caches', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'TTS 캐시',
                'verbose_name_plural': 'TTS 캐시',
                'db_table': 'voice_tts_cache',
                'ordering': ['-accessed_at'],
                'unique_together': {('user', 'text_hash')},
            },
        ),
    ]
