# Generated by Django 4.2.7 on 2025-09-20 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('envelope', '약봉투 글씨 인식'), ('schedule', '복용시간 인식'), ('appearance', '약 외관 식별')], max_length=20)),
                ('image', models.ImageField(upload_to='medicine_images/')),
                ('analysis_result', models.TextField(blank=True)),
                ('medicine_name', models.CharField(blank=True, max_length=200)),
                ('dosage_schedule', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '약물 분석',
                'verbose_name_plural': '약물 분석들',
            },
        ),
    ]
