# Generated by Django 5.2.7 on 2025-10-04 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('item_seq', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='품목기준코드')),
                ('item_name', models.CharField(db_index=True, max_length=500, verbose_name='제품명')),
                ('item_name_eng', models.CharField(blank=True, max_length=500, null=True, verbose_name='영문명')),
                ('entp_name', models.CharField(db_index=True, max_length=300, verbose_name='제조사')),
                ('effect', models.TextField(blank=True, null=True, verbose_name='효능/효과')),
                ('usage', models.TextField(blank=True, null=True, verbose_name='사용방법')),
                ('warning_critical', models.TextField(blank=True, null=True, verbose_name='주의사항 경고')),
                ('warning_general', models.TextField(blank=True, null=True, verbose_name='일반 주의사항')),
                ('interaction', models.TextField(blank=True, null=True, verbose_name='상호작용')),
                ('side_effect', models.TextField(blank=True, null=True, verbose_name='부작용')),
                ('storage', models.TextField(blank=True, null=True, verbose_name='보관방법')),
                ('main_ingredient', models.TextField(blank=True, null=True, verbose_name='주성분')),
                ('ingredient_count', models.IntegerField(blank=True, null=True, verbose_name='주성분 개수')),
                ('class_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='전문/일반')),
                ('product_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='분류')),
                ('edi_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='보험코드')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '의약품',
                'verbose_name_plural': '의약품 목록',
                'db_table': 'medicines',
            },
        ),
        migrations.CreateModel(
            name='AccessibilityInfo',
            fields=[
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='accessibility', serialize=False, to='medicines.medicine')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='음성/수어 영상')),
                ('has_audio', models.BooleanField(default=False, verbose_name='음성 가이드')),
                ('has_sign_language', models.BooleanField(default=False, verbose_name='수어 영상')),
                ('effect_tts', models.TextField(blank=True, null=True, verbose_name='효능(TTS)')),
                ('usage_tts', models.TextField(blank=True, null=True, verbose_name='사용법(TTS)')),
                ('warning_tts', models.TextField(blank=True, null=True, verbose_name='주의사항(TTS)')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='바코드')),
                ('std_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='표준코드')),
            ],
            options={
                'verbose_name': '접근성 정보',
                'db_table': 'accessibility_info',
            },
        ),
        migrations.CreateModel(
            name='PillIdentification',
            fields=[
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pill_info', serialize=False, to='medicines.medicine')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='이미지 URL')),
                ('shape', models.CharField(blank=True, max_length=100, null=True, verbose_name='모양')),
                ('color_front', models.CharField(blank=True, max_length=100, null=True, verbose_name='앞면 색상')),
                ('color_back', models.CharField(blank=True, max_length=100, null=True, verbose_name='뒷면 색상')),
                ('print_front', models.CharField(blank=True, max_length=200, null=True, verbose_name='앞면 각인')),
                ('print_back', models.CharField(blank=True, max_length=200, null=True, verbose_name='뒷면 각인')),
                ('length_long', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='장축')),
                ('length_short', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='단축')),
                ('thickness', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='두께')),
                ('line_front', models.CharField(blank=True, max_length=100, null=True, verbose_name='앞면 선')),
                ('line_back', models.CharField(blank=True, max_length=100, null=True, verbose_name='뒷면 선')),
                ('shape_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '낱알 정보',
                'db_table': 'pill_identification',
            },
        ),
    ]
