# Generated by Django 5.2.7 on 2025-10-07 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, max_length=100, null=True, verbose_name='투약량')),
                ('frequency', models.CharField(blank=True, max_length=100, null=True, verbose_name='복용횟수')),
                ('days', models.CharField(blank=True, max_length=50, null=True, verbose_name='복용기간')),
                ('prescription_date', models.DateField(blank=True, null=True, verbose_name='조제일자')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='등록일')),
                ('pharmacy_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='약국명')),
                ('hospital_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='병원명')),
                ('is_completed', models.BooleanField(default=False, verbose_name='복용완료')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 복용약',
                'verbose_name_plural': '사용자 복용약 목록',
                'db_table': 'user_medications',
                'ordering': ['-start_date'],
            },
        ),
    ]
